apiVersion: v1
data:
  AUTHORIZE_API: ${AUTHORIZE_API}
  MONGO_DB_URL: ${MONGO_DB_URL}
  MONGO_DB_USER: ${MONGO_DB_USER}
  MONGO_DB_NAME: ${MONGO_DB_NAME}
  REGION: ${REGION}
  LEGALTAG_API: ${LEGALTAG_API}
  org.opengroup.osdu.storage.disableAuth: "true"
kind: ConfigMap
metadata:
  labels:
    app: storage-reference
  name: storage-config
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generateName: storage-reference-anthos
  labels:
    app: storage-reference
  name: storage-reference
  namespace: default
spec:
  selector:
    matchLabels:
      app: storage-reference
  replicas: 1
  template:
    metadata:
      labels:
        app: storage-reference
    spec:
      containers:
        -   env:
              -   name: AUTHORIZE_API
                  valueFrom:
                    configMapKeyRef:
                      key: AUTHORIZE_API
                      name: storage-config
              -   name: MONGO_DB_URL
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_URL
                      name: storage-config
              -   name: MONGO_DB_USER
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_USER
                      name: storage-config
              -   name: MONGO_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: storage-secret
                      key: mongo.db.password
              -   name: MONGO_DB_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: MONGO_DB_NAME
                      name: storage-config
              -   name: MB_RABBITMQ_URI
                  valueFrom:
                    secretKeyRef:
                      name: storage-secret
                      key: mb.rabbitmq.uri
              -   name: REGION
                  valueFrom:
                    configMapKeyRef:
                      key: REGION
                      name: storage-config
              -   name: org.opengroup.osdu.storage.disableAuth
                  valueFrom:
                    configMapKeyRef:
                      key: org.opengroup.osdu.storage.disableAuth
                      name: storage-config
              -   name: MINIO_URL
                  valueFrom:
                    secretKeyRef:
                      key: minio.enpoint_url
                      name: storage-secret
              -   name: MINIO_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: minio.access_key
                      name: storage-secret
              -   name: MINIO_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      key: minio.secret_key
                      name: storage-secret
              -   name: MINIO_REGION
                  valueFrom:
                    secretKeyRef:
                      key: minio.region
                      name: storage-secret
              -   name: MINIO_BUCKET_RECORD_NAME
                  valueFrom:
                    secretKeyRef:
                      key: minio.bucket.record.name
                      name: storage-secret
            image: us.gcr.io/osdu-anthos-02/os-storage/anthos-storage-reference:9a1d20e-dirty
            name: storage-reference
---
apiVersion: v1
kind: Service
metadata:
  name: storage-reference
  namespace: default
spec:
  ports:
    -   protocol: TCP
        port: 80
        targetPort: 8080
  selector:
    app: storage-reference
  type: LoadBalancer
---
apiVersion: v1
data:
  mongo.db.password: ${MONGO_DB_PASSWORD}
  mb.rabbitmq.uri: ${MB_RABBITMQ_URI}
  minio.enpoint_url: ${MINIO_URL}
  minio.access_key: ${MINIO_ACCESS_KEY}
  minio.secret_key: ${MINIO_SECRET_KEY}
  minio.region: ${MINIO_REGION}
  minio.bucket.record.name: ${MINIO_RECORD_BUCKET_NAME}
kind: Secret
metadata:
  name: storage-secret
  namespace: default
type: Opaque
