# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - kuber-migration
  paths:
    exclude:
      - README.md
      - .gitignore

pool:
  name: Hosted Ubuntu 1604
  demands: maven

variables:
  buildMavenModules: storage-core,provider/storage-gcp
  dockerDir: provider/storage-gcp/docker
  imageName: os-storage-app
  deploymentDir: provider/storage-gcp/kubernetes/deployments
  deploymentFile: deployment-os-storage-service.yml

  integrationTestCorePom: testing/storage-test-core/pom.xml
  integrationTestGcpPom: testing/storage-test-gcp/pom.xml

steps:

  - task: DownloadSecureFile@1
    name: gcrKey
    inputs:
      secureFile: cicd-push-image-to-cr-keyfile.json

  - task: DownloadSecureFile@1
    name: kuberConfig
    inputs:
      secureFile: kubeconfig

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '--settings ./configuration/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN) -pl $(buildMavenModules) package'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - bash: |
      #!/bin/bash

      set -e
      pushd $(dockerDir)
      docker-compose build $(imageName)
      echo 'Image done.'
      cat $(gcrKey.secureFilePath) | docker login -u _json_key --password-stdin https://gcr.io
      echo 'Login done.'
      docker push gcr.io/opendes/$(imageName)
      echo 'Push done.'
      popd
      pushd $(deploymentDir)
      kubectl --kubeconfig $(kuberConfig.secureFilePath) delete -f $(deploymentFile)
      kubectl --kubeconfig $(kuberConfig.secureFilePath) apply -f $(deploymentFile)
      popd

      attempt_counter=0
      max_attempts=60
      
      #Wait storage service re-deployment

      until $(curl --head $(STORAGE_REDINESS_URL) --silent -o /dev/null --fail); do
      if [ ${attempt_counter} -eq ${max_attempts} ];then
          echo "Service is not available, integraton tests are skipped"
          exit 1
      fi

      printf '.'
      attempt_counter=$(($attempt_counter+1))
      sleep 2
      done

  - task: Maven@3
    inputs:
      mavenPomFile: '$(integrationTestCorePom)'
      options: '--settings ./configuration/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN) install'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: Maven@3
    inputs:
      mavenPomFile: '$(integrationTestGcpPom)'
      options: '--settings ./configuration/settings.xml -Dsurefire.useFile=false -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN) -DDEPLOY_ENV=$(DEPLOY_ENV) -DDOMAIN=$(DOMAIN) -DENVIRONMENT=$(ENVIRONMENT) -DGCLOUD_PROJECT=$(GCLOUD_PROJECT) -DINT_TEST_VENDOR=$(INT_TEST_VENDOR) -DINTEGRATION_TESTER=$(INTEGRATION_TESTER) -DLEGAL_URL=$(LEGAL_URL) -DNO_DATA_ACCESS_TESTER=$(NO_DATA_ACCESS_TESTER) -DSTORAGE_URL=$(STORAGE_URL) -DTENANT_GCP=$(TENANT_GCP) -DTENANT_NAME=$(TENANT_NAME) compile'
      publishJUnitResults: false
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

