apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.app_name }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  ENTITLEMENTS_HOST: "{{ .Values.data.entitlements_host }}"
  PARTITION_HOST: "{{ .Values.data.partition_host }}"
  LEGALTAG_HOST: "{{ .Values.data.legaltag_host }}"
  CRS_CONVERTER_HOST: "{{ .Values.data.crs_converter_host }}"
  LOG_LEVEL: "{{ .Values.data.log_level }}"
  GOOGLE_AUDIENCES: "{{ .Values.data.google_audiences }}"
  STORAGE_HOSTNAME: "{{ .Values.conf.app_name }}"
  REDIS_GROUP_HOST: "{{ .Values.data.redis_group_host }}"
  REDIS_STORAGE_HOST: "{{ .Values.data.redis_storage_host }}"
  DEFAULT_DATA_COUNTRY: "{{ .Values.data.default_data_country }}"
